"""
Measures actual token counts generated by the inference service for a set of card images.
Run from: C:\AI_Server\Coding\PTCG_2026\scripts\qwen-vl-finetune
"""
import os, sys, json, time, requests
from pathlib import Path

CACHE = Path("./image_cache")
URL = "http://localhost:8000/api/cards/extract-from-image"

imgs = sorted(CACHE.glob("*.jpg"))[:10]
if not imgs:
    print("No images in image_cache"); sys.exit(1)

results = []
for img in imgs:
    with open(img, "rb") as f:
        try:
            t0 = time.time()
            resp = requests.post(URL, files={"image": (img.name, f, "image/jpeg")}, timeout=120)
            elapsed = time.time() - t0
            data = resp.json()
            raw_text = data.get("raw_text", "")
            inf_ms = data.get("inference_time_ms", elapsed * 1000)
            # Rough token estimate from output length (~3.7 chars/token for JSON)
            out_chars = len(raw_text) if raw_text else len(json.dumps(data.get("data") or {}))
            est_tokens = max(1, round(out_chars / 3.7))
            results.append({
                "file": img.name,
                "inf_s": round(inf_ms / 1000, 1),
                "out_chars": out_chars,
                "est_tokens": est_tokens,
                "success": data.get("success", False),
            })
            print(f"  {img.name}: {inf_ms/1000:.1f}s  out_chars={out_chars}  ~{est_tokens} tokens")
        except Exception as e:
            print(f"  {img.name}: ERROR {e}")

if results:
    avg_s = sum(r["inf_s"] for r in results) / len(results)
    avg_tok = sum(r["est_tokens"] for r in results) / len(results)
    max_tok = max(r["est_tokens"] for r in results)
    print(f"\nAverage: {avg_s:.1f}s | Mean tokens: {avg_tok:.0f} | Max tokens: {max_tok}")
    print(f"Suggested max_new_tokens: {min(512, int(max_tok * 1.3))}")
