/**
 * Import Pokémon species multilingual names into the database and link
 * PrimaryCard records to their corresponding PokemonSpecies.
 *
 * Steps:
 *   1. Read data/pokemon_names.json (generated by scrape_pokemon_names.py)
 *   2. Upsert all species into the `pokemon_species` table
 *   3. Build lookup maps (nameJa → species, nameZhHant → species, nameEn → species)
 *   4. For each PrimaryCard, look at its linked Cards' (language, name) pairs
 *      and match against the lookup maps using exact → prefix matching.
 *   5. Update matching PrimaryCards with pokemonSpeciesId.
 *
 * Language → species field mapping:
 *   JA_JP  → nameJa
 *   ZH_TW  → nameZhHant  (Traditional Chinese — used by HK cards)
 *   EN_US  → nameEn
 *
 * Matching strategy:
 *   TCG card names include rule-box suffixes (e.g. "ピカチュウex", "Charizard ex").
 *   We first try an exact match, then a prefix match sorted by length descending
 *   so the longest (most specific) species name wins.
 *
 * Usage:
 *   npx tsx scrapers/import-pokemon-species.ts
 */

import { PrismaClient, LanguageCode } from '../packages/database/node_modules/.prisma/client';
import * as fs from 'fs';
import * as path from 'path';

const prisma = new PrismaClient();

interface SpeciesEntry {
  number: string;
  name_zh_hans: string;
  name_zh_hant: string;
  name_ja: string;
  name_en: string;
  form: string | null;
}

// ──────────────────────────────────────────────────────────────────────────────
// 1. Load JSON
// ──────────────────────────────────────────────────────────────────────────────

function loadSpeciesData(): SpeciesEntry[] {
  const p = path.resolve(__dirname, '../data/pokemon_names.json');
  if (!fs.existsSync(p)) {
    throw new Error(`pokemon_names.json not found at ${p}. Run scrape_pokemon_names.py first.`);
  }
  return JSON.parse(fs.readFileSync(p, 'utf-8'));
}

// ──────────────────────────────────────────────────────────────────────────────
// 2. Upsert species
// ──────────────────────────────────────────────────────────────────────────────

async function upsertSpecies(entries: SpeciesEntry[]): Promise<Map<string, string>> {
  console.log(`Upserting ${entries.length} species records...`);

  // Map dexNumber+form → db id (returned after upsert)
  const idMap = new Map<string, string>(); // key = `${dexNumber}|${form ?? ''}`

  // Batch in chunks of 200
  const CHUNK = 200;
  let done = 0;
  for (let i = 0; i < entries.length; i += CHUNK) {
    const chunk = entries.slice(i, i + CHUNK);
    await Promise.all(
      chunk.map(async (e) => {
        const record = await prisma.pokemonSpecies.upsert({
          where: {
            dexNumber_form: {
              dexNumber: e.number,
              form: e.form ?? '',
            },
          },
          update: {
            nameZhHans: e.name_zh_hans,
            nameZhHant: e.name_zh_hant,
            nameJa: e.name_ja,
            nameEn: e.name_en,
          },
          create: {
            dexNumber: e.number,
            form: e.form ?? '',
            nameZhHans: e.name_zh_hans,
            nameZhHant: e.name_zh_hant,
            nameJa: e.name_ja,
            nameEn: e.name_en,
          },
          select: { id: true },
        });
        idMap.set(`${e.number}|${e.form ?? ''}`, record.id);
      })
    );
    done += chunk.length;
    process.stdout.write(`  ${done}/${entries.length}\r`);
  }
  console.log(`  Done. ${idMap.size} species in DB.`);
  return idMap;
}

// ──────────────────────────────────────────────────────────────────────────────
// 3. Build lookup maps for matching
// ──────────────────────────────────────────────────────────────────────────────

interface SpeciesLookup {
  id: string;
  nameJa: string;
  nameZhHant: string;
  nameEn: string;
}

function buildLookupMaps(rows: SpeciesLookup[]): {
  byJa: Map<string, SpeciesLookup>;
  byZhHant: Map<string, SpeciesLookup>;
  byEn: Map<string, SpeciesLookup>;
  sortedJa: string[];
  sortedZhHant: string[];
  sortedEn: string[];
} {
  const byJa = new Map<string, SpeciesLookup>();
  const byZhHant = new Map<string, SpeciesLookup>();
  const byEn = new Map<string, SpeciesLookup>();

  for (const row of rows) {
    // Only set first occurrence (base form preferred over regional forms)
    if (!byJa.has(row.nameJa)) byJa.set(row.nameJa, row);
    if (!byZhHant.has(row.nameZhHant)) byZhHant.set(row.nameZhHant, row);
    if (!byEn.has(row.nameEn)) byEn.set(row.nameEn, row);
  }

  // Sorted by length desc for greedy prefix matching
  const sortedJa = [...byJa.keys()].sort((a, b) => b.length - a.length);
  const sortedZhHant = [...byZhHant.keys()].sort((a, b) => b.length - a.length);
  const sortedEn = [...byEn.keys()].sort((a, b) => b.length - a.length);

  return { byJa, byZhHant, byEn, sortedJa, sortedZhHant, sortedEn };
}

function findSpecies(
  cardName: string,
  language: LanguageCode,
  maps: ReturnType<typeof buildLookupMaps>
): SpeciesLookup | null {
  const { byJa, byZhHant, byEn, sortedJa, sortedZhHant, sortedEn } = maps;

  let exactMap: Map<string, SpeciesLookup>;
  let sortedNames: string[];
  let lookupMap: Map<string, SpeciesLookup>;

  if (language === LanguageCode.JA_JP) {
    exactMap = byJa;
    sortedNames = sortedJa;
    lookupMap = byJa;
  } else if (language === LanguageCode.ZH_TW) {
    exactMap = byZhHant;
    sortedNames = sortedZhHant;
    lookupMap = byZhHant;
  } else if (language === LanguageCode.EN_US) {
    exactMap = byEn;
    sortedNames = sortedEn;
    lookupMap = byEn;
  } else {
    return null;
  }

  // Exact match
  const exact = exactMap.get(cardName);
  if (exact) return exact;

  // Prefix match (longest species name first)
  for (const speciesName of sortedNames) {
    if (cardName.startsWith(speciesName)) {
      return lookupMap.get(speciesName)!;
    }
  }

  // Structured contains match for "trainer's Pokémon" style cards.
  // Only match when the species name appears immediately after a known
  // possessive particle to avoid false positives from substring coincidences.
  //   JA: ヒビキのホウオウex  → `の{name}`
  //   ZH: 小霞的喇叭芽        → `的{name}`
  //   EN: Brock's Onix       → `'s {name}` or `'s {name}`
  const particles =
    language === LanguageCode.JA_JP
      ? ['の']
      : language === LanguageCode.ZH_TW
        ? ['的']
        : ["'s ", '\u2019s ']; // straight and curly apostrophe

  for (const speciesName of sortedNames) {
    for (const particle of particles) {
      if (cardName.includes(particle + speciesName)) {
        return lookupMap.get(speciesName)!;
      }
    }
  }

  return null;
}

// ──────────────────────────────────────────────────────────────────────────────
// 4. Link PrimaryCards
// ──────────────────────────────────────────────────────────────────────────────

async function linkPrimaryCards(maps: ReturnType<typeof buildLookupMaps>): Promise<{
  linked: number;
  skipped: number;
  noMatch: number;
}> {
  console.log('Loading PrimaryCards with their linked cards...');

  // Collect all updates first, then batch-write.
  // Fetching with skip while modifying rows causes offset drift, so we
  // load all unlinked IDs first, then process each.
  const unlinkedIds = await prisma.primaryCard.findMany({
    where: { pokemonSpeciesId: null },
    select: { id: true },
  });
  console.log(`  ${unlinkedIds.length} PrimaryCards without species link`);

  const PAGE = 500;
  let linked = 0;
  let skipped = 0;
  let noMatch = 0;
  const updates: { id: string; pokemonSpeciesId: string }[] = [];

  for (let i = 0; i < unlinkedIds.length; i += PAGE) {
    const idChunk = unlinkedIds.slice(i, i + PAGE).map((r) => r.id);
    const primaryCards = await prisma.primaryCard.findMany({
      where: { id: { in: idChunk } },
      select: {
        id: true,
        cards: {
          select: { language: true, name: true, supertype: true },
        },
      },
    });

    for (const pc of primaryCards) {
      const pokemonCards = pc.cards.filter((c) => c.supertype === 'POKEMON');
      if (pokemonCards.length === 0) {
        skipped++;
        continue;
      }

      let match: SpeciesLookup | null = null;
      for (const card of pokemonCards) {
        match = findSpecies(card.name, card.language, maps);
        if (match) break;
      }

      if (!match) {
        noMatch++;
        continue;
      }

      updates.push({ id: pc.id, pokemonSpeciesId: match.id });
      linked++;
    }

    process.stdout.write(`  Processed ${Math.min(i + PAGE, unlinkedIds.length)}/${unlinkedIds.length}\r`);
  }

  // Batch update
  if (updates.length > 0) {
    console.log(`\n  Writing ${updates.length} updates...`);
    for (let i = 0; i < updates.length; i += PAGE) {
      const chunk = updates.slice(i, i + PAGE);
      await Promise.all(
        chunk.map((u) =>
          prisma.primaryCard.update({
            where: { id: u.id },
            data: { pokemonSpeciesId: u.pokemonSpeciesId },
          })
        )
      );
    }
  }

  console.log('');
  return { linked, skipped, noMatch };
}

// ──────────────────────────────────────────────────────────────────────────────
// 5. Main
// ──────────────────────────────────────────────────────────────────────────────

async function main() {
  console.log('='.repeat(60));
  console.log('POKÉMON SPECIES IMPORT & LINK');
  console.log('='.repeat(60));

  // Load source data
  const entries = loadSpeciesData();
  console.log(`Loaded ${entries.length} entries from pokemon_names.json`);

  // Upsert species records
  await upsertSpecies(entries);

  // Load all species from DB for lookup
  console.log('Building lookup maps...');
  const allSpecies = await prisma.pokemonSpecies.findMany({
    select: { id: true, nameJa: true, nameZhHant: true, nameEn: true },
  });
  const maps = buildLookupMaps(allSpecies);
  console.log(
    `  Maps built: ja=${maps.byJa.size}, zhHant=${maps.byZhHant.size}, en=${maps.byEn.size}`
  );

  // Link PrimaryCards
  // Always do a full re-link so the matching strategy is applied consistently.
  console.log('Resetting existing species links for full re-link...');
  await prisma.primaryCard.updateMany({ data: { pokemonSpeciesId: null } });
  console.log('  Done.');

  console.log('Linking PrimaryCards to species...');
  const { linked, skipped, noMatch } = await linkPrimaryCards(maps);

  // Summary
  const totalPrimary = await prisma.primaryCard.count();
  const linkedTotal = await prisma.primaryCard.count({ where: { pokemonSpeciesId: { not: null } } });

  console.log('\n' + '='.repeat(60));
  console.log('SUMMARY');
  console.log('='.repeat(60));
  console.log(`Species in DB         : ${allSpecies.length}`);
  console.log(`PrimaryCards total    : ${totalPrimary}`);
  console.log(`  Newly linked        : ${linked}`);
  console.log(`  Skipped (non-Pokémon): ${skipped}`);
  console.log(`  No species match    : ${noMatch}`);
  console.log(`  Total linked (all)  : ${linkedTotal}`);

  // Spot-check
  console.log('\nSpot-checks:');
  const checks = ['ピカチュウ', 'Pikachu', '比卡超'];
  for (const name of checks) {
    const pc = await prisma.primaryCard.findFirst({
      where: { name: { startsWith: name } },
      include: { pokemonSpecies: { select: { dexNumber: true, nameJa: true, nameEn: true, nameZhHant: true } } },
    });
    if (pc?.pokemonSpecies) {
      const s = pc.pokemonSpecies;
      console.log(`  "${pc.name}" → #${s.dexNumber} ${s.nameEn} / ${s.nameJa} / ${s.nameZhHant}`);
    } else if (pc) {
      console.log(`  "${pc.name}" → no species linked`);
    }
  }
}

main()
  .catch((e) => {
    console.error('Fatal error:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
